apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-registries-cm
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: pullsecret:argocd/ghcr-creds
