apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: personal-blog-updater
  namespace: argocd
spec:
  writeBackConfig:
        method: "git"
  namespace: argocd
  applicationRefs:
  - namePattern: personal-blog
    images:
    - alias: personal-blog
      imageName: ghcr.io/akash-pal/personal-blog
      commonUpdateSettings:
        updateStrategy: "newest-build"
        allowTags: "regexp:^[a-f0-9]{40}$"
        ignoreTags: ["latest"]
     