apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: personal-blog-updater
  namespace: argocd
spec:
  namespace: argocd
  commonUpdateSettings:
    updateStrategy: newest-build
    allowTags: "regexp:^[a-f0-9]{40}$"
  applicationRefs:
  - namePattern: personal-blog
    images:
    - alias: personal-blog
      imageName: ghcr.io/akash-pal/personal-blog
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: https://github.com/akash-pal/personal-blog
      branch: "main"